version: "3.9"

services:
  rustapp:
    container_name: rustapp
    image: game-community/rustapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DB_CONTAINER_NAME}://${DB_USERNAME}:${DB_PASSWORD}@db:8000/${DB_NAME}"

  db:
    container_name: db
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USERNAME
      - --pass
      - $DB_PASSWORD
    image: ${DB_CONTAINER_NAME}/${DB_CONTAINER_NAME}:latest
    ports:
      - 8000:8000
